services:
  backend:
    container_name: coins_backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      - python manage.py runserver
    environment:
      - SECRET_KEY=django-insecure-v-clcdthk(%!&0968lv(+@q3ozo1rya4j@-y3@dk-pq4vwvaz@
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=127.0.0.1
    depends_on:
      - redis


  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --save 60 1 --loglevel warning

  worker:
    container_name: coins_worker
    build: .
    volumes:
      - .:/app
    command: celery -A core worker --loglevel=info
    depends_on:
      - redis
      - backend
